/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        manrope: ["var(--font-manrope)", "sans-serif"],
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        fashion: {
          primary: "#1a1a2e",
          secondary: "#d4af37",
          accent: "#ff6b6b",
          neutral: "#2d2d2d",
          "base-100": "#f8f9fa",
          "base-200": "#e9ecef",
          "base-300": "#dee2e6",
          info: "#007bff",
          success: "#28a745",
          warning: "#ffc107",
          error: "#dc3545",
        },
        beauty: {
          primary: "#6a0572",
          secondary: "#e8b4b8",
          accent: "#f8b5c1",
          neutral: "#5a5a5a",
          "base-100": "#fdf6e3",
          "base-200": "#f4e6d7",
          "base-300": "#e8d5c4",
          info: "#17a2b8",
          success: "#28a745",
          warning: "#ffc107",
          error: "#dc3545",
        },
        gadgets: {
          primary: "#007bff",
          secondary: "#343a40",
          accent: "#ff6b35",
          neutral: "#6c757d",
          "base-100": "#f8f9fa",
          "base-200": "#e9ecef",
          "base-300": "#dee2e6",
          info: "#17a2b8",
          success: "#28a745",
          warning: "#ffc107",
          error: "#dc3545",
        },
        furniture: {
          primary: "#8b4513",
          secondary: "#9caf88",
          accent: "#f5f5dc",
          neutral: "#6b5b73",
          "base-100": "#ffffff",
          "base-200": "#f8f9fa",
          "base-300": "#e9ecef",
          info: "#17a2b8",
          success: "#28a745",
          warning: "#ffc107",
          error: "#dc3545",
        },
        kidsmom: {
          primary: "#a8a8d8",
          secondary: "#98d8c8",
          accent: "#ff7f7f",
          neutral: "#64748b",
          "base-100": "#e6f3ff",
          "base-200": "#dbeafe",
          "base-300": "#bfdbfe",
          info: "#3b82f6",
          success: "#10b981",
          warning: "#f59e0b",
          error: "#ef4444",
        },
      },
      "light",
      "dark",
    ],
  },
};
